name: Deploy Flask App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    env:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: set up docker compose continue-on-error: 
        uses: docker/setup-compose-action@v2
      - name: deploy with docker compose
        run: docker-compose down && docker compose up -d --build --force-recreate
      
