---
#this is workflow name 
name: Hello Amrit

#runs on automatic trigger whenever change is pushed to branch (deployment)
on:
  push:
    branches: [ main ]
      
#these are jobs inside workflows 
jobs:

#this is name of the job 
  greet:
  #this is a github runner, each job runs on a runner
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "heloo amrit "
      - name: say hello to username
        run: echo "hello $USER"
        
  show-versions:
      runs-on: ubuntu-latest
      steps:
        - name: Version of python docker etc 
          run: docker --version && python --version
