name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "staging"

jobs:
  manualwork:
    runs-on: ubuntu-latest

    steps:
      - name: Print environment 
        run: echo "Running deployment for environment: ${{ github.event.inputs.environment }}"
