name: Run Real Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x scripts/test.sh

      - name: Run test script
        run: ./scripts/test.sh
