name: Secret Message

on:
  workflow_dispatch:

jobs:

  show-secret-message:
    runs-on: ubuntu-latest
    steps:
      - name: check if secret exist
        run: |
          if [ -z "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "Secret not set"
          else
            echo "The secret is set: true"
          fi

      - name: Attempt to print secret
        run: echo "Secret value is:${{ secrets.MY_SECRET_MESSAGE }}"
