name: Self Hosted

on:
  workflow_dispatch: 


jobs:
  testself-hosted-runner:
    runs-on: self-hosted
    steps:
       - name: hostname of machine
         run: hostname
       - name: working directory
         run: pwd
       - name: create a file and verify
         run: echo "this is for testing purpose " >> test.txt
       - name: verify the file
         run: ls -la
